#!/usr/bin/python

import sys

argv_size = len(sys.argv) - 1

# if parameter count is not 2
if argv_size != 2:
	print(
		f"Invalid parameter count '{argv_size}' to 'termux_tasker_basic_python_test'",
		file=sys.stderr,
	)
	print(f'{" ".join(sys.argv[1:])}', file=sys.stderr)
	sys.exit(1)

print(f"$1=`{sys.argv[1]}`")
print(f"$2=`{sys.argv[2]}`")

sys.exit(0)
